name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 🔧 Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  pipeline:
    name: 🧪 Run Pipeline Scripts
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Step 1 - Initial Data Check
        run: python src/initial_data_check.py

      - name: Step 2 - Feature Encoding
        run: python src/feature_encoding.py

      - name: Step 3 - Model Comparison
        run: python src/comparison_train_model.py

      - name: Step 4 - Model Tuning
        run: python src/tuning_selected_model.py

      - name: Step 5 - Train Best Model
        run: python src/train_best_model.py

  tests:
    name: ✅ Run Unit Tests
    runs-on: ubuntu-latest
    needs: pipeline

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: pytest tests/ -v --disable-warnings

  dashboard-check:
    name: 🖥️ Check Dashboard Syntax
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Syntax Check on Dashboard Scripts
        run: |
          python -m py_compile student_dashboard/final_UI_dashboard.py
          python -m py_compile student_dashboard/mvd_dashboard.py
          python -m py_compile student_dashboard/predictive_dashboard.py
